[services]
backend = "backend"
frontend = "frontend"

[phases]
# Backend configuration
backend.build = "pnpm install && pnpm build"
backend.start = "pnpm start"

# Frontend configuration
frontend.build = "pnpm install && pnpm run build"
frontend.start = "pnpm run preview"